<?php

namespace app\controllers;
use app\models\User;
use yii\helpers\Console;

class AppController extends \yii\web\Controller{

    public function beforeAction($action){
        if(!\Yii::$app->user->isGuest){

            try {
                \Yii::$app->user->identity->last_activity = nowdate();
                \Yii::$app->user->identity->save();
            }catch (\Exception $e){}

            if(\Yii::$app->user->identity->block){
                \Yii::$app->user->logout(true);
                showError("Вы были заблокированы","Внимание",10000);
                return $this->redirect("/");
            }

            if(! User::isAdmin()) {
                $denyUsers = [
                    "admin" => ["*"],
                    "category"=>["link-features","index","change-parent","rename","add","update","delete"],
                    "feature"=>["index",'view',"create","update","delete"],
                    "department"=>["change-parent","mark-children","set-dep","index","rename","add","update","delete"],
                    "dictinary"=>["index","rename","add","update","delete"],

                ];
                if (isset($denyUsers[$this->id])) {
                    $allow = true;
                    if (in_array("*", $denyUsers[$this->id]))
                        $allow = false;
                    if (in_array($this->action->id, $denyUsers[$this->id]))
                        $allow = false;
                    if (!$allow)
                        throw new \yii\web\ForbiddenHttpException('Вам запрещен доступ на эту страницу');
                }
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }




}