<?php

namespace app\models;

use Yii;
use yii\web\ForbiddenHttpException;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property int $is_can_add
 * @property string|null $name
 * @property int $is_hidden
 * @property int $is_deleted
 * @property int $sort_id
 * @property int|null $parent_id
 *
 * @property Category[] $categories
 * @property Category[] $categoryId1s
 * @property Category[] $categoryId2s
 * @property Feature[] $features
 * @property Item[] $items
 * @property Category $parent
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'string'],
            [['id'], 'unique'],
            [['parent_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::class, 'targetAttribute' => ['parent_id' => 'id']],
        ];
    }

    public function beforeSave($insert)
    {
        if(!User::isAdmin())
            throw new ForbiddenHttpException("Вам запрещен доступ к изменению категорий!");
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_can_add' => 'Is Can Add',
            'name' => 'Name',
            'is_hidden' => 'Is Hidden',
            'is_deleted' => 'Is Deleted',
            'sort_id' => 'Sort ID',
            'parent_id' => 'Parent ID',
        ];
    }

    /**
     * Gets query for [[Categories]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::class, ['parent_id' => 'id']);
    }

    /**
     * Gets query for [[CategoryId1s]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryId1s()
    {
        return $this->hasMany(Category::class, ['id' => 'category_id_1'])->viaTable('category_to_category', ['category_id_2' => 'id']);
    }

    /**
     * Gets query for [[CategoryId2s]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryId2s()
    {
        return $this->hasMany(Category::class, ['id' => 'category_id_2'])->viaTable('category_to_category', ['category_id_1' => 'id']);
    }

    /**
     * Gets query for [[CategoryToCategories]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryToCategories()
    {
        return $this->hasMany(CategoryToCategory::class, ['category_id_1' => 'id']);
    }

    /**
     * Gets query for [[CategoryToCategories0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryToCategories0()
    {
        return $this->hasMany(CategoryToCategory::class, ['category_id_2' => 'id']);
    }

    /**
     * Gets query for [[Featurecategories]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getFeaturecategories()
    {
        return $this->hasMany(Featurecategories::class, ['Category_id' => 'id']);
    }

    /**
     * Gets query for [[Features]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getFeatures()
    {
        return $this->hasMany(Feature::class, ['id' => 'Feature_id'])->viaTable('featurecategories', ['Category_id' => 'id'])->orderBy(["sort_id"=>SORT_DESC]);
    }

    /**
     * Gets query for [[Items]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->hasMany(Item::class, ['category_id' => 'id']);
    }

    /**
     * Gets query for [[Parent]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getParent()
    {
        return $this->hasOne(Category::class, ['id' => 'parent_id']);
    }
}
