<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * This is the model class for table "department".
 *
 * @property int $id
 * @property string|null $name
 * @property int $sort_id
 * @property int|null $parent_id
 * @property int $is_deleted
 * @property int $is_department
 *
 * @property Department[] $allChildrens
 * @property Department[] $departments
 * @property Employee[] $employees
 * @property Employee[] $responsibles
 * @property Item[] $items
 * @property Department $parent
 * @property Department $unit
 * @property Transfer[] $transfers
 * @property Transfer[] $transfers0
 */
class Department extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'department';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'sort_id', 'parent_id', 'is_deleted','is_department'], 'integer'],
            [['name'], 'string'],
            [['id'], 'unique'],
            [['parent_id'], 'exist', 'skipOnError' => true, 'targetClass' => Department::class, 'targetAttribute' => ['parent_id' => 'id']],
        ];
    }
    public function getResponsibles(){
        $all = $this->getIdsAllUnitDepartmentsWithUnit();
        return Employee::find()->where(["is_responsible"=>true])->andFilterWhere(["in","department_id",$all])->all();

    }
    public function getUnit(){
        if($this->is_department)
            return $this->parent->unit;
        return $this;
    }

    public function getIdsAllUnitDepartmentsWithUnit(){
        $unit = $this->unit;
        $all = ArrayHelper::getColumn($unit->getChildrensOnlyDepartments(),"id");
        array_push($all,$unit->id);
        return $all;
    }
    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'sort_id' => 'Sort ID',
            'parent_id' => 'Parent ID',
            'is_deleted' => 'Is Deleted',
            'is_department' => 'Это отдел?',
        ];
    }

    /**
     * Gets query for [[Departments]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDepartments()
    {
        return $this->hasMany(Department::class, ['parent_id' => 'id']);
    }

    /**
     * Gets query for [[Employees]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getEmployees()
    {
        return $this->hasMany(Employee::class, ['department_id' => 'id']);
    }

    /**
     * Gets query for [[Items]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->hasMany(Item::class, ['department_id' => 'id']);
    }
    public function canAccess(){
        return in_array($this->id,\Yii::$app->user->identity->getAccessDepartments());
    }
    public function getAllChildrens(){
        $allDeps = [];
        foreach ($this->departments as $d){
            array_push($allDeps,$d);
            $allDeps = array_merge($allDeps,$d->allChildrens);
        }
        return $allDeps;
    }
    public function getChildrensOnlyDepartments(){//Вернуть только вложенные ОТДЕЛЫ(департаменты) этого подраздкеления
        $allDeps = [];
        foreach ($this->departments as $d){
            if(!$d->is_department)
                continue;
            array_push($allDeps,$d);
            $allDeps = array_merge($allDeps,$d->allChildrens);
        }
        return $allDeps;
    }
    public static function getListDepartments(){
        return ArrayHelper::map(Department::find()->all(),"id","name");
    }
    /**
     * Gets query for [[Parent]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getParent()
    {
        return $this->hasOne(Department::class, ['id' => 'parent_id']);
    }
    public function beforeSave($insert){
        if(!User::isAdmin())
                throw new ForbiddenHttpException("Вам запрещен доступ к изменению подразделений!");

        if($this->is_department && $this->parent_id == null)
            throw new ForbiddenHttpException("Подразделение самого высокого уровня вложенности не может быть помечено как департамент!");
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * Gets query for [[Transfers]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTransfers()
    {
        return $this->hasMany(Transfer::class, ['department_id_from' => 'id']);
    }

    /**
     * Gets query for [[Transfers0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTransfers0()
    {
        return $this->hasMany(Transfer::class, ['department_id_to' => 'id']);
    }
}
