<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;
use yii\web\ForbiddenHttpException;

/**
 * This is the model class for table "employee".
 *
 * @property int $id
 * @property string|null $first_name
 * @property string|null $second_name
 * @property string|null $last_name
 * @property string|null $post
 * @property string|null $cabinet
 * @property int $is_deleted
 * @property int $is_responsible
 * @property int $sort_id
 * @property int $department_id
 *
 * @property Item[] $itemsResponsible
 * @property Department $department
 * @property Department[] $advancedDepartments
 * @property Item[] $items
 */
class Employee extends \yii\db\ActiveRecord
{
    public $_advancedDepartments = null;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'employee';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['first_name', 'second_name', 'last_name', 'post', 'cabinet'], 'string'],
            [[ 'department_id','first_name','second_name','last_name'], 'required'],
            [['fio','advancedDepartments'], 'safe'],
            [['is_deleted', 'sort_id', 'department_id','is_responsible'], 'integer'],
            [['department_id'], 'exist', 'skipOnError' => true, 'targetClass' => Department::class, 'targetAttribute' => ['department_id' => 'id']],
        ];
    }
    public function beforeSave($insert)
    {
        if(!$this->department->canAccess())
            throw new ForbiddenHttpException("Вам запрещен доступ к подразделнию '{$this->department->name}'!");

        if(!$this->is_responsible)
            $this->unlinkAll('advancedDepartments',true);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterSave($insert, $changedAttributes)
    {
        $this->unlinkAll('advancedDepartments',true);
        if(!is_null($this->_advancedDepartments) && is_array($this->_advancedDepartments)){
            foreach ($this->_advancedDepartments as $dep){
                    $this->link('advancedDepartments', $dep);
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_name' => 'Имя',
            'second_name' => 'Фамилия',
            'last_name' => 'Отчество',
            'post' => 'Должность',
            'cabinet' => 'Кабинет',
            'advancedDepartments' => 'Дополнительно открыть возможность выбора мат.ответвенного для следующих подразделений (не обязательно)',
            'is_deleted' => 'Is Deleted',
            'sort_id' => 'Sort ID',
            'department_id' => 'Подразделение',
            'is_responsible' => 'Материально отвественный',
        ];
    }

    public function getFullName(){
        return "$this->second_name $this->first_name $this->last_name";
    }
    public function getShortName(){
        $n =  "$this->second_name ";
        if(mb_strlen($this->first_name)>1)
            $n.=mb_substr($this->first_name,0,1).".";
        if(mb_strlen($this->last_name)>1)
            $n.=mb_substr($this->last_name,0,1).".";
        return $n;
    }

    /**
     * Gets query for [[Department]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDepartment()
    {
        return $this->hasOne(Department::class, ['id' => 'department_id']);
    }
    public function getItemsResponsible()
    {
        return $this->hasMany(Item::class, ['responsible_employee_id' => 'id']);
    }
    public function getAdvancedDepartments(){
        return $this->hasMany(Department::class, ['id' => 'department_id'])
            ->viaTable('advanced_departments', ['employee_id' => 'id']);
    }
    public function setAdvancedDepartments($v){
        $this->_advancedDepartments =  Department::find()->where(["in","id",$v])->all();
    }

    /**
     * Gets query for [[Items]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->hasMany(Item::class, ['employee_id' => 'id']);
    }
}
