<?php

namespace app\models;

use Yii;
use yii\web\ForbiddenHttpException;

/**
 * This is the model class for table "feature".
 *
 * @property int $id
 * @property int $is_required
 * @property int|null $dictinary_id
 * @property int $sort_id
 * @property string|null $name
 * @property string|null $type
 *
 * @property Category[] $categories
 * @property Dictinary $dictinary
 * @property FeatureValue[] $featureValues
 * @property Featurecategories[] $featurecategories
 * @property Field[] $fields
 */
class Feature extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'feature';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name','type'], 'required'],
            [['id', 'is_required', 'dictinary_id', 'sort_id'], 'integer'],
            [['type'], 'string'],
            [['name'], 'string', 'max' => 255],
            [['id'], 'unique'],
            [['dictinary_id'], 'exist', 'skipOnError' => true, 'targetClass' => Dictinary::class, 'targetAttribute' => ['dictinary_id' => 'id']]
        ];
    }




    public static function getTypesList(){
        return [
          "string"=>"Строка",
          "text"=>"Многострочное текстовое поле",
          "int"=>"Целое число",
          "double"=>"Дробное число",
          "list"=>"Список из словаря",
          "date"=>"Дата",
          "bool"=>"Булево значение(да\нет)"
        ];
    }
    public function beforeSave($insert)
    {

        if(!User::isAdmin())
            throw new ForbiddenHttpException("Вам запрещен доступ к изменению Feature!");
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_required' => 'Обязательное для заполнения поле',
            'dictinary_id' => 'Словарь',
            'sort_id' => 'Приоритет сортировки',
            'name' => 'Название',
            'type' => 'Тип поля',
        ];
    }

    /**
     * Gets query for [[Categories]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::class, ['id' => 'Category_id'])->viaTable('featurecategories', ['Feature_id' => 'id']);
    }


    /**
     * Gets query for [[Dictinary]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDictinary()
    {
        return $this->hasOne(Dictinary::class, ['id' => 'dictinary_id']);
    }

    /**
     * Gets query for [[FeatureValues]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getFeatureValues()
    {
        return $this->hasMany(FeatureValue::class, ['feature_id' => 'id']);
    }

    /**
     * Gets query for [[Fields]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getFields()
    {
        return $this->hasMany(Field::class, ['feature_id' => 'id']);
    }
}
