<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "history".
 *
 * @property string $name
 * @property string $id
 * @property string $data
 * @property string $department
 * @property string $category
 * @property string $inv_num
 * @property string $date
 * @property string $action
 */
class History extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'history';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'id', 'data',  'action'], 'required'],
            [['data','department','category'], 'string'],
            [['date','id'], 'safe'],
            [['name',  'inv_num', 'action'], 'string', 'max' => 255],
        ];
    }
public function beforeSave($insert)
{

    $this->date = nowdate();

    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
}

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'name' => 'Name',
            'id' => 'ID',
            'data' => 'Data',
            'inv_num' => 'Inv Num',
            'date' => 'Date',
            'action' => 'Action',
        ];
    }
}
