<?php

namespace app\models;

use app\models\Item;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;

/**
 * ItemSearch represents the model behind the search form of `app\models\Item`.
 */
class ItemSearch extends Item{
    public $searchTags = null;
    public $typeShow = null;
    public $stateTech = null;
    public $showWithDeps = null;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'inv_num', 'workspace', 'name', 'date_change','searchTags','responsible_employee_id','typeShow','showWithDeps','stateTech'], 'safe'],
            [['employee_id', 'category_id', 'is_written_off', 'department_id'], 'integer'],
        ];
    }
    public function attributeLabels()
    {

        return array_merge(parent::attributeLabels(),[
            "searchTags"=>"Теги"
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Item::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort'=> ['defaultOrder' => ['date_change' => SORT_DESC]],
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }


        // grid filtering conditions
        $query->andFilterWhere([
            'employee_id' => $this->employee_id,
            'category_id' => $this->category_id,
            'date_change' => $this->date_change,
            'is_written_off' => $this->is_written_off,
        ]);

        if(isShowAllItems()){

            $query->andFilterWhere([
                'in','department_id', $this->department->getIdsAllUnitDepartmentsWithUnit()]);

        }
        else{
            $query->andFilterWhere([
                'department_id' => $this->department_id]);
        }


        $query->andFilterWhere(['like', 'id', $this->id])
            ->andFilterWhere(['like', 'inv_num', $this->inv_num])
            ->andFilterWhere(['like', 'workspace', $this->workspace])
            ->andFilterWhere(['like', 'name', $this->name]);

        if(is_array($this->searchTags)){
            $ids = ArrayHelper::getColumn(Item::find()->joinWith(['tags' => function (ActiveQuery $query) {
                return $query
                    ->andWhere(["in","tags.id",$this->searchTags]);
            }])->all(),"id");
            $query->andFilterWhere(["in",'id',$ids]);
        }

        return $dataProvider;
    }
    public function searchAll($params){
        $query = Item::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort'=> ['defaultOrder' => ['date_change' => SORT_DESC]],
        ]);

        $this->load($params);


        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }
		
		
		if($this->showWithDeps === "1" && $this->department != null){
			$query->andFilterWhere([
				"in","department_id",$this->department->unit->getIdsAllUnitDepartmentsWithUnit()
			]);
		}else{
			$query->andFilterWhere([
				"department_id"=>$this->department_id
			]);
		}

        // grid filtering conditions
        $query->andFilterWhere([
            'employee_id' => $this->employee_id,
            'category_id' => $this->category_id,
            'responsible_employee_id' => $this->responsible_employee_id,
            'date_change' => $this->date_change,
            'is_written_off' => $this->is_written_off,
        ]);


        $query->andFilterWhere(['like', 'id', $this->id])
            ->andFilterWhere(['like', 'inv_num', $this->inv_num])
            ->andFilterWhere(['like', 'workspace', $this->workspace])
            ->andFilterWhere(['like', 'name', $this->name]);


        if(is_array($this->searchTags)){
            $ids = ArrayHelper::getColumn(Item::find()->joinWith(['tags' => function (ActiveQuery $query) {
                return $query
                    ->andWhere(["in","tags.id",$this->searchTags]);
            }])->all(),"id");
            $query->andWhere(["in",'id',$ids]);
        }


        if($this->stateTech != null){

            $techStateFeatId = \app\models\Feature::find()->where(["name"=>"Текущее состояние"])->one()->id;
            $ids = ArrayHelper::getColumn(FeatureValue::find()->where(["feature_id"=>$techStateFeatId,"value"=>$this->stateTech])->all(),"item_id");
            $query->andWhere(["in",'id',$ids]);
        }

        $depsAccess = \Yii::$app->user->identity->getAccessDepartments(true);
        
		
		$query->having(["in","department_id",$depsAccess]);
		

        if($this->typeShow == "issued"){
            $query->andHaving(["not",['employee_id'=> null]]);
            $query->orHaving("(TRIM(workspace) <> '' AND workspace IS NOT NULL )");
        }
        if($this->typeShow == "notissued"){
            $query->andHaving(['employee_id'=> null]);
			$query->andHaving("(TRIM(workspace) = ''  OR workspace IS NULL )");
        }
		

        return $dataProvider;
    }
}
