<?php

namespace app\models;

use Yii;
use yii\db\Exception;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\ForbiddenHttpException;

/**
 * This is the model class for table "item".
 *
 * @property string $id
 * @property int|null $employee_id
 * @property int|null $responsible_employee_id
 * @property int $category_id
 * @property string|null $inv_num
 * @property string|null $workspace
 * @property string|null $name
 * @property string|null $date_change
 * @property int $is_written_off
 * @property int $department_id
 *
 * @property Category $category
 * @property Department $department
 * @property Employee $responsible_employee
 * @property Employee $employee
 * @property FeatureValue[] $featureValues
 * @property Item[] $items
 * @property Item $parent
 * @property Repair[] $repairs
 * @property Tag[] $tags
 * @property Transfer[] $transfers
 */
class Item extends \yii\db\ActiveRecord{

    public $feats;
    public $edittags;
    public $ignoreAllow = false;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'item';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [[ 'category_id', 'department_id','responsible_employee_id','name'], 'required'],
            [['employee_id', 'category_id', 'is_written_off', 'department_id','responsible_employee_id','id'], 'integer'],
            [['workspace'], 'string'],
            [['date_change','feats','edittags'], 'safe'],
            [['inv_num'], 'string', 'max' => 50],
            [['name'], 'string', 'max' => 250],
            [['id'], 'unique'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::class, 'targetAttribute' => ['category_id' => 'id']],
            [['department_id'], 'exist', 'skipOnError' => true, 'targetClass' => Department::class, 'targetAttribute' => ['department_id' => 'id']],
            [['employee_id'], 'exist', 'skipOnError' => true, 'targetClass' => Employee::class, 'targetAttribute' => ['employee_id' => 'id']],
            [['responsible_employee_id'], 'exist', 'skipOnError' => true, 'targetClass' => Employee::class, 'targetAttribute' => ['responsible_employee_id' => 'id']],
        ];
    }
    public function beforeDelete()
    {
        if(!$this->department->canAccess())
            throw new ForbiddenHttpException("У вас нет доступа к средвам подразделения '".$this->department->name."'!");

        saveHistory($this,[],"delete");
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public  const SCENARIO_CREATE_EDIT = "CREATE_EDIT";
    public function validate($attributeNames = null, $clearErrors = true)
    {
        if($this->department != null && $this->employee != null && $this->employee->department_id != $this->department_id){
            $this->addError("employee_id","Данный сотрудник не является сотрудником выбранного подразделения!");
        }


        if(is_array($this->feats)){
        foreach ($this->category->features as $f){
            if($f->is_required){
                    if(!isset($this->feats[$f->id]) || empty($this->feats[$f->id]))
                        $this->addError("feats[$f->id]","Необходимо заполнить «{$f->name}».");
                }
            }
        }
        return parent::validate($attributeNames, false); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert){
        $this->date_change = nowdate();

        if(!$this->ignoreAllow && !$this->department->canAccess())
            throw new ForbiddenHttpException("Вам запрещен доступ к подразделнию '{$this->department->name}'!");

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'employee_id' => 'Сотрудник',
            'category_id' => 'Категория',
            'inv_num' => 'Инвентарный номер',
            'workspace' => 'Местонахождение',
            'name' => 'Наименование',
            'date_change' => 'Дата изменения',
            'is_written_off' => 'Списан',
            'department_id' => 'Подразделение',
            'responsible_employee_id' => 'Материально ответственное лицо',
        ];
    }

    /**
     * Gets query for [[Category]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::class, ['id' => 'category_id']);
    }

    /**
     * Gets query for [[Department]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDepartment()
    {
        return $this->hasOne(Department::class, ['id' => 'department_id']);
    }


    /**
     * Gets query for [[Employee]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getEmployee()
    {
        return $this->hasOne(Employee::class, ['id' => 'employee_id']);
    }
    /**
     * Gets query for [[Employee]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getResponsibleEmployee()
    {
        return $this->hasOne(Employee::class, ['id' => 'responsible_employee_id']);
    }

    /**
     * Gets query for [[FeatureValues]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getFeatureValues()
    {
        return $this->hasMany(FeatureValue::class, ['item_id' => 'id']);
    }


    /**
     * Gets query for [[Repairs]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRepairs()
    {
        return $this->hasMany(Repair::class, ['item_id' => 'id']);
    }

    /**
     * Gets query for [[Tags]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTags()
    {
        return $this->hasMany(Tag::class, ['id' => 'tag_id'])->viaTable('tags_items', ['Item_id' => 'id']);
    }


    /**
     * Gets query for [[Transfers]].
     *
     * @return \yii\db\ActiveQuery
     */

    public function getTransfers()
    {
        return $this->hasMany(Transfer::class, ['id' => 'transfer_id'])->viaTable('transfer_items', ['item_id' => 'id']);
    }

    /**
     * Gets query for [[WrittenOffs]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getWrittenOffs()
    {
        return $this->hasMany(WrittenOff::class, ['item_id' => 'id']);
    }
}
