<?php

namespace app\models;

use Yii;
use yii\web\ForbiddenHttpException;

/**
 * This is the model class for table "transfer".
 *
 * @property string $id
 * @property string|null $date
 * @property int $item_id
 * @property string|null $description
 * @property string|null $workplace_from
 * @property string|null $workplace_to
 * @property int $department_id_from
 * @property int $department_id_to
 * @property string $date_change
 * @property string $type
 *
 * @property Employee $responsible_employee_id_to
 * @property Department $departmentIdFrom
 * @property Department $departmentIdTo
 * @property Item $item
 */
class Transfer extends \yii\db\ActiveRecord
{
    public $ignoreAllow = false;
    public  $employee_to_id = null;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'transfer';
    }
    public  static function GetTypes(){
        return [
          "internal"=>"Перемещение по подразделению",
          "external"=>"Перемещение в другое подразделение",
        ];
    }
    public  function DisplayType(){
        if(in_array($this->type,array_keys(self::GetTypes())))
            return self::GetTypes()[$this->type];
        return $this->type;
    }
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [[  'department_id_from', 'department_id_to','type'], 'required'],
            [['date','responsible_employee_id_to','employee_to_id'],'safe'],
            [[ 'date_change'], 'safe'],
            [[ 'department_id_from', 'department_id_to'], 'integer'],
            [['description', 'workplace_from', 'workplace_to'], 'string'],
            [['id'], 'string', 'max' => 128],
            [['id'], 'unique'],
            [['department_id_from'], 'exist', 'skipOnError' => true, 'targetClass' => Department::class, 'targetAttribute' => ['department_id_from' => 'id']],
            [['department_id_to'], 'exist', 'skipOnError' => true, 'targetClass' => Department::class, 'targetAttribute' => ['department_id_to' => 'id']],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Дата перемещения',
            'description' => 'Описание',
            'workplace_from' => 'Из местоположения',
            'workplace_to' => 'На местоположение',
            'type' => 'Тип перемещния',
            'department_id_from' => 'Из подразделения',
            'employee_to_id' => 'К сотруднику',
            'department_id_to' => 'В подразделение',
            'date_change' => 'Дата изменения',
            'responsible_employee_id_to' => 'Материально ответственный',
        ];
    }



    public function beforeSave($insert)    {
        if(!$this->ignoreAllow && !$this->departmentFrom->canAccess())
            throw new ForbiddenHttpException("Вам запрещен доступ к исходному подразделнию '{$this->departmentFrom->name}'!");

        $this->date_change = nowdate();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * Gets query for [[DepartmentIdFrom]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDepartmentFrom()
    {
        return $this->hasOne(Department::class, ['id' => 'department_id_from']);
    }

    /**
     * Gets query for [[DepartmentIdTo]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDepartmentTo()
    {
        return $this->hasOne(Department::class, ['id' => 'department_id_to']);
    }

    public function getItems()
    {
        return $this->hasMany(Item::class, ['id' => 'item_id'])->viaTable('transfer_items', ['transfer_id' => 'id']);
    }
}
