<?php

namespace app\models;

use Yii;
use yii\base\BaseObject;
use yii\data\ArrayDataProvider;
use yii\debug\DbAsset;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property string $name
 * @property string $login
 * @property string $pwd_hash
 * @property string $password
 * @property string $role
 * @property string $authKey
 * @property string $accessToken
 * @property bool $block
 * @property Tag[] $tags
 */
class User extends \yii\db\ActiveRecord  implements \yii\web\IdentityInterface
{
    /**
     * {@inheritdoc}
     */
    public $password = "";
    public $departmentsAccess = "";

    public $new_password;     // новый пароль
    public $confirm_password; // подтверждение пароля

    const SCENARIO_UPDATE = 'update';
    const SCENARIO_CHANGE_PWD = 'changePassword';

    function __construct($config = [])
    {
        $this->role = DataExt::ROLE_USER;
        parent::__construct($config);
    }

    public static function tableName()
    {
        return 'users';
    }
    public function scenarios()
    {
        return [
            self::SCENARIO_DEFAULT => ['name','login', 'password','role','departmentsAccess'],
            self::SCENARIO_UPDATE => ['name','login', 'role','departmentsAccess'],
            self::SCENARIO_CHANGE_PWD =>['new_password', 'confirm_password']
        ];
    }
    public function rules()
    {
        return [
            [['name', 'login'], 'required'],
            ['password','required','when'=>function(){
                return $this->isNewRecord;
            },'on'=> self::SCENARIO_DEFAULT],
            ['role',function($attr,$paraams){
                if(!in_array($this->role,DataExt::getRoles()))
                    $this->addError($attr, 'Неверная роль');
            }],
            ['login',function($attr,$paraams){
                $us =User::findByUsername($this->login);
                if($us && ($this->isNewRecord || (!$this->isNewRecord && $this->id != $us->id ))) {
                    $this->addError($attr, 'Такой логин уже занят');
                }

            }],
            [['password'], 'string', 'min' => 6],
            [['departmentsAccess','last_activity'],'safe'],
            [['name', 'login', 'password'], 'string', 'max' => 255],
            [['new_password', 'confirm_password'], 'required', 'on' => 'changePassword'],
            ['new_password', 'string', 'min' => 6],
            ['confirm_password', 'compare', 'compareAttribute' => 'new_password', 'message' => 'Пароли не совпадают.'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'login' => 'Логин',
            'pwd_hash' => 'Pwd Hash',
            'last_activity' => 'Последняя активность',
            'role' => 'Роль',
            'password' => 'Пароль',
            'new_password' => 'Новый пароль',
            'confirm_password' => 'Повторите пароль',
            'departmentsAccess' => 'Доступ к подразделениям',
        ];
    }


    /**
     * Gets query for [[TrableSolutionHistories]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsername(){
        return $this->login;
    }

    public function getTags()
    {
        return $this->hasMany(Tag::class, ['user_id' => 'id']);
    }
    public function afterSave($insert, $changedAttributes){

        Rule::deleteAll(["and",["permission"=>"department"],["user_id"=>$this->id]]);

        if(!is_array($this->departmentsAccess))
            $this->departmentsAccess =[];

        if($this->role != DataExt::ROLE_ADMIIN)
            foreach ($this->departmentsAccess as $v){
                $r = new Rule();
                $r->user_id  = $this->id;
                $r->permission = "department";
                $r->value = $v;
                $r->save();

            }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

        public function getAccessDepartments($onlyIds = true){//получить ids подразделений к которым есть доступ
            $ids = [];
            if($this->role == DataExt::ROLE_ADMIIN)
                $ids =  ArrayHelper::getColumn( Department::find()->all(),"id");
            else
                $ids = ArrayHelper::getColumn( Rule::find()->where(["permission"=>"department"])->andWhere(["user_id"=>$this->id])->all(),"value");
            if(!$onlyIds)
                return Department::find()->where(["in","id",$ids])->all();
            return $ids;


        }

    public function afterFind()    {
        if($this->role == DataExt::ROLE_ADMIIN)
            $this->departmentsAccess = ArrayHelper::getColumn(Department::find()->all(),"id");
        else
            $this->departmentsAccess = ArrayHelper::getColumn( Rule::find()->where(["permission"=>"department"])->andWhere(["user_id"=>$this->id])->all(),"value");

        parent::afterFind(); // dTODO: Change the autogenerated stub
    }

    public static function isAdmin(){
        if(!Yii::$app->user->isGuest && $user = User::findOne(["id"=>Yii::$app->user->id]))
            return $user->role == DataExt::ROLE_ADMIIN;
        return false;
    }


    public static function findIdentity($id)
    {
        return User::findOne(["id"=>$id]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return self::findOne(["accessToken"=>$token]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return self::findOne(["login"=>$username]);
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)    {
        return Yii::$app->getSecurity()->validatePassword($password,$this->pwd_hash);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRule()
    {
        return $this->hasMany(Rule::class, ['user_id' => 'id']);
    }

}
